#!/bin/sh
ffmpeg -listen 1 -i 'rtmp://192.168.1.17:6645/stream/test12345' -c:v copy -c:a copy  -flags +cgop -g 60 -lhls 1 -hls_time 2 -hls_list_size 1 -hls_allow_cache 1 -hls_flags delete_segments -flush_packets 1 stream.m3u8; \cp -f done.m3u8 stream.m3u8;

